### PR TITLE
Rename struct NVML to Nvml

### PR DESCRIPTION
**Pull request by TheJltres**
This PR should solve #16 

I'm starting with Rust, and for a project I need NVML library, and searching for C/C++ native builds, I found this repo, and while I was reading the docs, I thought of helping a little :smile:

I think I covered all documentation

### CODE REVIEW

**Comment by Cldfire** [comment]
Thanks for thinking of helping and putting this PR together! It's looking great so far and I really appreciate it :).

CI is failing for reasons unrelated to this PR; I'm going to go fix that up and open a separate PR to resolve that.

In the meantime, one thing we should add to this PR is a changelog entry. I'm thinking something like the following would work well:

```diff
 # nvml-wrapper Changelog
 
 This file describes the changes / additions / fixes between wrapper releases, tracked in a loose version of the [keep a changelog](https://keepachangelog.com/en/1.0.0/) format.
 
 ## [Unreleased]
 
+ ### Changed
+ 
+ * The `NVML` struct has been renamed to `Nvml` (#22 - @TheJltres)
+
 ### Dependencies
 
 * `libloading`: `0.6.6` -> `0.7.0`
 
 ### Internal
 
 * Re-organized repo using a workspace
 * Tests that can't be run on my machine are now ignored with the `#[ignore]` attribute. The `test-local` feature has been removed as a result
 
 ## [0.7.0] (released 2020-12-06)
```

**Comment by Cldfire** [comment]
Ok, if you merge master into this PR CI will be happy now :)

**Comment by TheJltres** [comment]
Sorry, totally forgot about the Changelog

The merge is done 🚀

**Comment by Cldfire** [comment]
Sweet, thank you! And no worries on the changelog, I forget it sometimes too.

**Pull request merged**
